apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: default
  labels:
    app: spring-app
spec:
  replicas: 3
  minReadySeconds: 45
  selector:
    matchLabels:
      app: spring-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - image: 486912667928.dkr.ecr.us-east-1.amazonaws.com/spring-app:1
          imagePullPolicy: IfNotPresent
          name: spring-app
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 125m
              memory: 120Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30