apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    apps: spring-demo
  name: spring-demo
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: spring-demo
  sessionAffinity: None
  type: LoadBalancer 
#If we don´t specify a service type, ClusterIP is going to be the default ServiceType.