apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: default
  labels:
    app: spring-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - image: 486912667928.dkr.ecr.us-east-1.amazonaws.com/spring-app:3
          imagePullPolicy: Always
          name: spring-app
          ports:
            - containerPort: 8080
              protocol: TCP