apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    apps: spring-app
  name: spring-app
  # annotations:
  #     service.beta.kubernetes.io/aws-load-balancer-internal: "false"
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring-app
  sessionAffinity: None
  type: LoadBalancer 
#If we don´t specify a service type, ClusterIP is going to be the default ServiceType.