apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: default
  labels:
    app: spring-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: spring-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - image: {{ .Values.spring.image }}:{{ .Values.version }}
          imagePullPolicy: Always
          name: spring-app
          ports:
            - containerPort: 8080
              protocol: TCP
